language: node_js
node_js:
- node
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y zip
install:
- npm install
script:
- gulp dist
- sh ./deploy_travisci.sh
env:
  global:
  - GH_COLOR_ARTIFACT_REPO: github.com/garystafford/fav-color-artifacts.git
  - secure: cAll+P5WyOyAza9NK4L3ZfWoCC4vc1Hle51qPhubo71aHOEQxyL1zIMC2ucuBZXgrjNJG8azXh/eW8Q1/P2uoM7nlrPivFEvEFQ8ZyUamT037xz07blyHJxnBRq54H/Jlp42yl0p3ahhFJcIgSipzueQJfukotscRviyEHD0MxksH5n7Re0x+9ITMw+Aq3NznI5aCBQ8L7bPNL2fj4nKaPV5Jqvb6uQeg4GZNEm/yvKdwFIxiK7p6P5it8TIWPtieOYWvpLpClxROKIWejmHUN1NXe12CNB48rKTSC14mDE6pU/0N0dU/leWAanJvkD6FS8TxFN0fvBD4n6LlIQdqDSDa8T5JuOcSObeqvJ516JhFUAljHs/WXyqbiwbLvoqHwtATG3ooMRcwl/IgcgQyu2UW7ClJeVzYghnE66fydJ9ykAItV1CkXj1bJLFITNjcCyt6Wn4hNGAJh35+SFMMNILEtHLzX8LlIg/K8+Uhzt3QQ4HEsvusWwhDiaHYPn4tpbWTMltnfLNeWwQ+kBH7HSJ6g7R8T/yxAfrOcv5C0IYd69oIYNFzF0UVYvhzy1wVO8H+a0dxcId7XAM+Tsk4tVNLo6l2VWpA7x/qLLldPMm23NiPItl7J3n3eP2E6haN7sIKlgFPar6xoFZXugVemA8Sj6IvOFFAJ2wb0vCBZc=
  - secure: cFGIObkZ4jE0EjVMxx8LHaiIoRzC4hGETl5lugQahleW+zbDN4UJ26U8URAQbGyIULUu8gKVBRDJwpOndjtTR+y0x/KSnM62RkyruaDwo/WK3JbeBLZlvBp9Bp45uS2EjUzUO9crU1QUXlX5EBeT+AkRHlWYehWkrkl/PiBSEQBQXKo3kv+xGFWvvbrpUnAo7Gaj6nKS3hpsMRK17Nl5LUIseBLdcbl7ecqB6ClMY6YRT/+yd4RtkwiKRoQwfpLGFMRXpN6d7JMUh0J3c5BdmRutkFiG0cLEAs8Gdw+UwIvnoyk5b89wZjwwZ5HK+YMQsA8jjGdM2Lt3RuLkqyxPQFLRWUJOzDxZ6ZRSoXqgTAvx6oQcsLZBSRNxXXavjVuX4uZRYFhxByQgyjkgf0liQz1HMvL69iPs5TyXdvrM5QYZntkox3J8kfHlydjLtYiBfdBp7aARbDdqqtacMPvw2PhOwT1Uwp8C7qVjvYXa/gnIlD/VU/+U6gjJNvTK5syFLUG3W+p73aI52pdbzCPlKIiqdq/2HQJqIVLmF57R6DWKxz84bljzhCQV4+5Bxw4hA509fL8K6CBQeMyghNtYijL+0AdWFLH4rSl0QvlhWz8Y115SR1PjyDOENMBFWZ4N2c8UFrX67BTm6s5ykzpuK725F9nx3kjjRuQKijlsYJc=
notifications:
  slack:
    secure: ylEfOVSkwDC/dR8SzpG/3N1+G85VLIZd46Umljj1T1xyKiUNmj+hNs1jFPJE1himxG3C/xElyRb2jLHzZ8r+kodqpkLFQ/aJzOIXt86OD1iVaBRBmwWu5J/6b6Dab9zxCQf6HH/b23fEUYFBxzM0tGWBkuoZ55nzXz4/FIKPJDFjGIOiExk8Sf1zuSRMuYauU/0s5SzaKkM89bTTrPVdTqB7d1RXyEpzm2+JAK323IlsQJi18vaXPzjEjy2uqqIGn5C1MT3xUup+Oq1AWsQoyE7EykvQNWBT3nm45RSN6Mh/gDSr0NWirEkZEmgvACLMIVdkDLQOFxv7zuSWiHxwDcQo9Fox+GmBdhpNPazpl4d3fPfIGmA8JgCMV8ZGrQLpL0kn62G0xIonrkcew8FHKfF191XGUzjohIApguJDPrfz4B4A2USVd49rIFMO4vYB0FuCEeHA+dwA065rjCvACJ7zHD5BuDIlXoZDBCYbpaQ+8C2nEjH78i7HkA38FgEyAwpaLRYglDRS0ktXuBIaEgP+HjQdDyI/6gLvpEmprH5NMc0u4mB0T4Et7AEGzZZdXiCgHZFzFJ0MhlqZmQpdR/ScDNk+MAu7oXpZPY36QySaqrSEhZAMXWl90N/0ikFjQhahluFlm3c41+7Cqn4iIB8lt3jV1eEWLG7l+LNfSgM=
